services:
  - type: web
    name: handwritten-digit-backend
    runtime: python
    plan: free
    rootDir: neural_network_2/backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 180
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0

  - type: web
    name: handwritten-digit-frontend
    runtime: static
    rootDir: neural_network_2/frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: handwritten-digit-backend
          envVarKey: RENDER_EXTERNAL_HOSTNAME
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
